# Generated by Django 2.0 on 2017-12-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0010_auto_20171215_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Personal Computer', 'Personal computer'), ('Monoblock', 'Monoblock')], default='Personal Computer', max_length=30),
        ),
    ]
