# Generated by Django 2.0.2 on 2018-03-31 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copmuters', '0011_auto_20171225_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='computer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Personal Computer', 'Personal computer'), ('Monoblock', 'Monoblock'), ('Laptop', 'Laptop')], default='Personal Computer', max_length=30),
        ),
        migrations.AddField(
            model_name='computer',
            name='tag',
            field=models.ManyToManyField(to='copmuters.Tag'),
        ),
    ]
