# Generated by Django 2.0.2 on 2018-03-31 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copmuters', '0012_auto_20180331_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('correct', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Personal Computer', 'Personal computer'), ('Monoblock', 'Monoblock')], default='Personal Computer', max_length=30),
        ),
        migrations.AddField(
            model_name='answer',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copmuters.Computer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copmuters.Customer'),
        ),
    ]
