# Generated by Django 2.0.2 on 2018-05-09 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copmuters', '0014_auto_20180508_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Monoblock', 'Monoblock'), ('Personal Computer', 'Personal computer')], default='Personal Computer', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
