# Generated by Django 2.0.2 on 2018-05-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copmuters', '0015_auto_20180509_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Personal Computer', 'Personal computer'), ('Monoblock', 'Monoblock'), ('Laptop', 'Laptop')], default='Personal Computer', max_length=30),
        ),
    ]
