# Generated by Django 2.0.2 on 2018-06-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copmuters', '0016_auto_20180511_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Personal Computer', 'Personal computer'), ('Laptop', 'Laptop'), ('Monoblock', 'Monoblock')], default='Personal Computer', max_length=30),
        ),
    ]
