# Generated by Django 2.0.2 on 2018-06-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copmuters', '0017_auto_20180604_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Monoblock', 'Monoblock'), ('Personal Computer', 'Personal computer')], default='Personal Computer', max_length=30),
        ),
    ]
